import { Geist, Geist_Mono } from "next/font/google";
import { 
  ClerkProvider, 
  SignedIn, 
  SignedOut, 
  SignIn
} from '@clerk/nextjs'
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="min-h-screen min-w-screen flex flex-col items-center justify-center gap-3">
              <SignedIn>
                {children}
              </SignedIn>
              <SignedOut>
                <SignIn routing="hash" />
              </SignedOut> 
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
